server:
    port: 8080
spring:
    application:
        name: todo-tracker
    datasource:
        url: jdbc:postgresql://localhost:5432/todotracker
        username: todotracker
        password: todotracker
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true
    profiles:
        active: default

